import guava from "../../assets/guava.jpg";
interface Tree {
  id: number;
  name: string;
  type: string;
  age: string;
  price: string;
  description: string;
  image: string;
}
const trees: Tree[] = [
  {
    id: 1,
    name: "Oak Tree",
    type: "Oak",
    age: "3 years",
    price: "$50",
    description: "A strong and beautiful oak tree, perfect for any garden.",
    image: `${guava}`,
  },
  {
    id: 2,
    name: "Pine Tree",
    type: "Pine",
    age: "5 years",
    price: "$80",
    description: "A tall pine tree that brings nature closer to you.",
    image: `${guava}`,
  },
  {
    id: 3,
    name: "Maple Tree",
    type: "Maple",
    age: "4 years",
    price: "$60",
    description: "A vibrant maple tree with colorful leaves.",
    image: `${guava}`,
  },
  {
    id: 4,
    name: "Birch Tree",
    type: "Birch",
    age: "2 years",
    price: "$40",
    description: "A slender birch tree, ideal for small gardens.",
    image: `${guava}`,
  },
  {
    id: 5,
    name: "Cedar Tree",
    type: "Cedar",
    age: "6 years",
    price: "$90",
    description: "A fragrant cedar tree, known for its strong wood.",
    image: `${guava}`,
  },
  {
    id: 6,
    name: "Willow Tree",
    type: "Willow",
    age: "7 years",
    price: "$100",
    description: "A weeping willow tree, adding elegance to any landscape.",
    image: `${guava}`,
  },
  {
    id: 7,
    name: "Spruce Tree",
    type: "Spruce",
    age: "4 years",
    price: "$70",
    description: "A classic spruce tree, perfect for holiday decorations.",
    image: `${guava}`,
  },
  {
    id: 8,
    name: "Cherry Blossom Tree",
    type: "Cherry",
    age: "3 years",
    price: "$120",
    description: "A beautiful cherry blossom tree, known for its pink flowers.",
    image: `${guava}`,
  },
  {
    id: 9,
    name: "Redwood Tree",
    type: "Redwood",
    age: "10 years",
    price: "$200",
    description: "A majestic redwood tree, a symbol of strength and longevity.",
    image: `${guava}`,
  },
  {
    id: 10,
    name: "Apple Tree",
    type: "Apple",
    age: "5 years",
    price: "$75",
    description: "A fruit-bearing apple tree, providing delicious apples.",
    image: `${guava}`,
  },
  {
    id: 11,
    name: "Pear Tree",
    type: "Pear",
    age: "6 years",
    price: "$85",
    description: "A pear tree that will produce sweet pears.",
    image: `${guava}`,
  },
  {
    id: 12,
    name: "Lemon Tree",
    type: "Citrus",
    age: "2 Years",
    price: "$65",
    description: "A lemon tree perfect for your patio.",
    image: `${guava}`,
  },
  {
    id: 13,
    name: "Olive Tree",
    type: "Olive",
    age: "8 Years",
    price: "$110",
    description: "A classic olive tree, with beautiful silver leaves.",
    image: `${guava}`,
  },
  {
    id: 14,
    name: "Dogwood Tree",
    type: "Dogwood",
    age: "4 Years",
    price: "$95",
    description: "A dogwood tree with stunning spring blooms.",
    image: `${guava}`,
  },
  {
    id: 15,
    name: "Sycamore Tree",
    type: "Sycamore",
    age: "7 years",
    price: "$130",
    description: "A large sycamore tree, providing ample shade.",
    image: `${guava}`,
  },
  {
    id: 16,
    name: "Ash Tree",
    type: "Ash",
    age: "5 years",
    price: "$70",
    description: "A resilient ash tree, known for its strong timber.",
    image: `${guava}`,
  },
  {
    id: 17,
    name: "Elm Tree",
    type: "Elm",
    age: "6 years",
    price: "$80",
    description: "A graceful elm tree, adding charm to any landscape.",
    image: `${guava}`,
  },
  {
    id: 18,
    name: "Cypress Tree",
    type: "Cypress",
    age: "9 years",
    price: "$150",
    description: "A tall cypress tree, perfect for creating privacy.",
    image: `${guava}`,
  },
  {
    id: 19,
    name: "Fig Tree",
    type: "Fig",
    age: "3 Years",
    price: "$75",
    description: "A fig tree that produces sweet figs.",
    image: `${guava}`,
  },
  {
    id: 20,
    name: "Plum Tree",
    type: "Plum",
    age: "4 Years",
    price: "$85",
    description: "A plum tree with delicious fruit.",
    image: `${guava}`,
  },
  {
    id: 21,
    name: "Walnut Tree",
    type: "Walnut",
    age: "8 Years",
    price: "$140",
    description: "A walnut tree that produces edible walnuts.",
    image: `${guava}`,
  },
  {
    id: 22,
    name: "Hazelnut Tree",
    type: "Hazelnut",
    age: "5 Years",
    price: "$90",
    description: "A hazelnut tree that produces tasty hazelnuts.",
    image: `${guava}`,
  },
  {
    id: 23,
    name: "Chestnut Tree",
    type: "Chestnut",
    age: "7 Years",
    price: "$120",
    description: "A chestnut tree that produces edible chestnuts.",
    image: `${guava}`,
  },
  {
    id: 24,
    name: "Juniper Tree",
    type: "Juniper",
    age: "6 Years",
    price: "$100",
    description: "A juniper tree with aromatic berries.",
    image: `${guava}`,
  },
  {
    id: 25,
    name: "Larch Tree",
    type: "Larch",
    age: "4 Years",
    price: "$80",
    description: "A larch tree with soft needles.",
    image: `${guava}`,
  },
  {
    id: 26,
    name: "Poplar Tree",
    type: "Poplar",
    age: "3 Years",
    price: "$60",
    description: "A poplar tree that grows quickly.",
    image: `${guava}`,
  },
  {
    id: 27,
    name: "Magnolia Tree",
    type: "Magnolia",
    age: "5 Years",
    price: "$110",
    description: "A magnolia tree with large, fragrant flowers.",
    image: `${guava}`,
  },
  {
    id: 28,
    name: "Beech Tree",
    type: "Beech",
    age: "9 Years",
    price: "$160",
    description: "A beech tree with smooth, gray bark.",
    image: `${guava}`,
  },
  {
    id: 29,
    name: "Holly Tree",
    type: "Holly",
    age: "6 Years",
    price: "$95",
    description: "A beech tree with smooth, gray bark.",
    image: `${guava}`,
  },
];

export { trees };
export type { Tree };
